import { useEffect, useState } from "react";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import api from "../services/api";

function Orders() {
  const [orders, setOrders] =
    useState([]);

  const [customers, setCustomers] =
    useState([]);

  const [products, setProducts] =
    useState([]);

  const [search, setSearch] =
    useState("");

  const [form, setForm] =
    useState({
      customer_id: "",
      product_id: "",
      quantity: "",
    });

  const fetchData = async () => {
    const ordersRes =
      await api.get("/orders/");

    const customersRes =
      await api.get("/customers/");

    const productsRes =
      await api.get("/products/");

    setOrders(ordersRes.data);
    setCustomers(
      customersRes.data
    );
    setProducts(productsRes.data);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSubmit = async (
    e
  ) => {
    e.preventDefault();

    try {
      await api.post(
        "/orders/",
        {
          customer_id: Number(
            form.customer_id
          ),

          items: [
            {
              product_id: Number(
                form.product_id
              ),

              quantity: Number(
                form.quantity
              ),
            },
          ],
        }
      );

      alert(
        "Order Created Successfully"
      );

      setForm({
        customer_id: "",
        product_id: "",
        quantity: "",
      });

      fetchData();
    } catch (err) {
      alert(
        err.response?.data
          ?.detail || "Error"
      );
    }
  };

  const deleteOrder = async (
    id
  ) => {
    if (
      !window.confirm(
        "Delete Order?"
      )
    )
      return;

    try {
      await api.delete(
        `/orders/${id}`
      );

      fetchData();
    } catch {
      alert(
        "Unable to delete order"
      );
    }
  };

  const exportCSV = () => {
    const csv = [
      "OrderID,CustomerID,TotalAmount",

      ...orders.map(
        (o) =>
          `${o.id},${o.customer_id},${o.total_amount}`
      ),
    ].join("\n");

    const blob = new Blob(
      [csv],
      {
        type:
          "text/csv;charset=utf-8;",
      }
    );

    saveAs(
      blob,
      "orders.csv"
    );
  };

 const downloadInvoice = (order) => {
  const customer = customers.find(
    (c) => c.id === order.customer_id
  );

  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("INVOICE", 20, 20);

  // Company Name
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text(
    "Inventory Management System",
    20,
    45
  );

  // Invoice Info
  doc.setFontSize(12);

  doc.text(
    `Invoice No: INV-${order.id}`,
    20,
    65
  );

  doc.text(
    `Date: ${new Date().toLocaleDateString()}`,
    20,
    75
  );

  // Customer Details
  doc.setFontSize(14);

  doc.text(
    "Customer Details",
    20,
    95
  );

  doc.line(20, 98, 80, 98);

  doc.setFontSize(12);

  doc.text(
    `Customer Name: ${
      customer?.full_name ||
      "Unknown"
    }`,
    20,
    110
  );

  doc.text(
    `Customer ID: ${order.customer_id}`,
    20,
    120
  );

  // Order Summary
  doc.setFillColor(
    240,
    240,
    240
  );

  doc.rect(
    20,
    140,
    170,
    12,
    "F"
  );

  doc.text(
    "Order ID",
    30,
    148
  );

  doc.text(
    "Total Amount",
    120,
    148
  );

  doc.rect(
    20,
    152,
    170,
    15
  );

  doc.text(
    String(order.id),
    35,
    162
  );

  doc.text(
    `Rs ${order.total_amount}`,
    120,
    162
  );

  // Grand Total
  doc.setFillColor(
    37,
    99,
    235
  );

  doc.rect(
    110,
    190,
    80,
    18,
    "F"
  );

  doc.setTextColor(
    255,
    255,
    255
  );

  doc.setFontSize(14);

  doc.text(
    `Total: Rs ${order.total_amount}`,
    118,
    202
  );

  // Footer
  doc.setTextColor(
    100,
    100,
    100
  );

  doc.setFontSize(10);

  doc.text(
    "Thank you for your business.",
    20,
    270
  );

  doc.text(
    "Generated by Inventory Management System",
    20,
    278
  );

  doc.save(
    `Invoice_${order.id}.pdf`
  );
};

  const filteredOrders =
    orders.filter((order) =>
      String(order.id).includes(
        search
      )
    );

  return (
    <>
      <h1 className="page-title">
        Orders
      </h1>

      <div className="table-container">
        <h2
          style={{
            marginBottom: "20px",
          }}
        >
          Create Order
        </h2>

        <form
          onSubmit={handleSubmit}
        >
          <select
            value={
              form.customer_id
            }
            onChange={(e) =>
              setForm({
                ...form,
                customer_id:
                  e.target.value,
              })
            }
            required
          >
            <option value="">
              Select Customer
            </option>

            {customers.map(
              (customer) => (
                <option
                  key={
                    customer.id
                  }
                  value={
                    customer.id
                  }
                >
                  {
                    customer.full_name
                  }
                </option>
              )
            )}
          </select>

          <select
            value={
              form.product_id
            }
            onChange={(e) =>
              setForm({
                ...form,
                product_id:
                  e.target.value,
              })
            }
            required
          >
            <option value="">
              Select Product
            </option>

            {products.map(
              (product) => (
                <option
                  key={
                    product.id
                  }
                  value={
                    product.id
                  }
                >
                  {
                    product.name
                  }
                </option>
              )
            )}
          </select>

          <input
            type="number"
            placeholder="Quantity"
            value={
              form.quantity
            }
            onChange={(e) =>
              setForm({
                ...form,
                quantity:
                  e.target.value,
              })
            }
            required
          />

          <div className="form-button">
            <button type="submit">
              Create Order
            </button>
          </div>
        </form>
      </div>

      <br />

      <div className="table-container">
        <div
          style={{
            display: "flex",
            justifyContent:
              "space-between",
            alignItems:
              "center",
            marginBottom:
              "20px",
          }}
        >
          <h2>
            Total Orders :
            {" "}
            {
              filteredOrders.length
            }
          </h2>

          <button
            onClick={
              exportCSV
            }
          >
            📥 Export CSV
          </button>
        </div>

        <input
          className="search-box"
          type="text"
          placeholder="Search Order ID..."
          value={search}
          onChange={(e) =>
            setSearch(
              e.target.value
            )
          }
        />

        <table>
          <thead>
            <tr>
              <th>
                Order ID
              </th>

              <th>
                Customer
              </th>

              <th>
                Total Amount
              </th>

              <th>
                Invoice
              </th>

              <th>
                Delete
              </th>
            </tr>
          </thead>

          <tbody>
            {filteredOrders.map(
              (order) => (
                <tr
                  key={order.id}
                >
                  <td>
                    {order.id}
                  </td>

                  <td>
                    {
                      customers.find(
                        (c) =>
                          c.id ===
                          order.customer_id
                      )?.full_name
                    }
                  </td>

                  <td>
                    ₹
                    {
                      order.total_amount
                    }
                  </td>

                  <td>
                    <button
                      onClick={() =>
                        downloadInvoice(
                          order
                        )
                      }
                    >
                      PDF
                    </button>
                  </td>

                  <td>
                    <button
                      className="action-btn"
                      onClick={() =>
                        deleteOrder(
                          order.id
                        )
                      }
                    >
                      Delete
                    </button>
                  </td>
                </tr>
              )
            )}
          </tbody>
        </table>
      </div>
    </>
  );
}

export default Orders;